### ISSUE TITLE
Error calculation query

### ISSUE THREAD

**Issue by TBGAnsell** [delemottelab/allosteric-pathways#2]
Hello, I am running the pipeline on a protein-lipid system (one chain). I get very different information flow values if I run the protocol with all 5 repeats vs running on individual repeats and averaging post-processing (for the protein and the ligands). 

I guess my question really relates on how best to report error. Ideally I'd like to report the values calculated using all replicates as these are probably more reasonable - I was running on individual repeats in order to get the standard deviation/standard error between repeats but now I am concerned by the change in the mean information flow values.

For reference the simulation length is comparable to those reported in your paper. Any advice here would be appreciated.

**Comment by anniewesterlund** [comment]
Hello,

Then I would suggest to run each simulation replicate in the analysis pipeline independently and calculate the mean and standard deviation on the obtained profiles afterwards.

Best,
Annie

**Comment by TBGAnsell** [comment]
Dear Annie,

How is the information flow being averaged when all repeats are provided? Why do I get different mean information flows between the individual and combined means? Is it something to do with how the values are normalised?

Best,

Bertie
________________________________

**Comment by anniewesterlund** [comment]
Hi Bertie,

This depends a little on what your system is, and how you specify input paramters.
Essentially, no averaging over different information flows is done unless you input a homomer with multiple chains and specify n_chains (> 1). In that case, the averaging is done across subunits in your protein. Otherwise, your entire dataset is treated as one dataset which gives rise to measurement written to:
`self.out_directory_ + 'current_flow_betweenness_' + self.file_end_name_ + '.npy'`

What we did in this paper: https://doi.org/10.1063/5.0020974 on the single-chained GPCR, was to divide the simulations into three chunks and compute average and stddev using the resulting three information flow profile afterwards. I would not be surprised if there is some difference between using the full dataset to get one point estimate of the information flow compared to using three and averaging (sampling effects etc. which may be more prominent). 

Hope this helps,
Annie

**Comment by TBGAnsell** [comment]
Dear Annie,

Ok thanks you for your help. Interpretation of the information flow for the bound ligand differs quite substaintaing between the two analyses but I will take you word for it and use the individual replicates.

Best wishes,

Bertie
________________________________

**Comment by anniewesterlund** [comment]
Ok. Just a final note: The individual replicate analysis should in principle be better in such a case, since you also get the error estimate which could help remove focus from uncertain residues.

Closing issue :)
